name: nmap
version: 7.12SVN-0.4
summary: Network mapping tool.
description: Network mapping tool.
architectures: [amd64, armhf]

apps:
    nmap:
        command: bin/nmap
        plugs: [network, network-bind]
    ncat:
        command: bin/ncat
        plugs: [network, network-bind]
    nping:
        command: bin/nping
        plugs: [network, network-bind]
parts:
    nmap:
        plugin: autotools
        source: https://github.com/nmap/nmap
